# Generated by Django 4.1.2 on 2022-11-07 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request_buy', '0003_alter_requestbuy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbuy',
            name='rieltor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
