# Generated by Django 4.1.2 on 2022-11-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_buy', '0006_requestbuy_no_attention'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbuy',
            name='last_time_edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestbuy',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
