# Generated by Django 4.1.2 on 2022-11-03 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Активная', 'Активная'), ('Горячая', 'Горячая'), ('Теплая', 'Теплая')], default='Активная', max_length=30)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('rooms_area', models.IntegerField(blank=True, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('levels', models.IntegerField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('Без ремонта', 'Без ремонта'), ('Средний ремонт', 'Средний ремонт'), ('Евро ремонт', 'Евро ремонт')], default='Средний ремонт', max_length=20)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('start_price', models.IntegerField(blank=True, null=True)),
                ('end_price', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apartment.apartment')),
            ],
            options={
                'verbose_name': 'Заявка на продажу',
                'verbose_name_plural': 'Заявки на продажу',
            },
        ),
    ]
