# Generated by Django 4.1.2 on 2022-11-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_sell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestsell',
            name='area',
        ),
        migrations.RemoveField(
            model_name='requestsell',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='requestsell',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='requestsell',
            name='date',
        ),
        migrations.RemoveField(
            model_name='requestsell',
            name='end_price',
        ),
        migrations.RemoveField(
            model_name='requestsell',
            name='levels',
        ),
        migrations.RemoveField(
            model_name='requestsell',
            name='location',
        ),
        migrations.RemoveField(
            model_name='requestsell',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='requestsell',
            name='rooms_area',
        ),
        migrations.RemoveField(
            model_name='requestsell',
            name='start_price',
        ),
        migrations.RemoveField(
            model_name='requestsell',
            name='status',
        ),
    ]
