# Generated by Django 4.1.2 on 2022-11-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_sell', '0002_remove_requestsell_area_remove_requestsell_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsell',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
