# Generated by Django 4.1.2 on 2022-11-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_sell', '0003_requestsell_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsell',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestsell',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestsell',
            name='condition',
            field=models.CharField(choices=[('Без ремонта', 'Без ремонта'), ('Средний ремонт', 'Средний ремонт'), ('Евро ремонт', 'Евро ремонт')], default='Средний ремонт', max_length=20),
        ),
        migrations.AddField(
            model_name='requestsell',
            name='end_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestsell',
            name='levels',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestsell',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='requestsell',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestsell',
            name='rooms_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestsell',
            name='start_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestsell',
            name='status',
            field=models.CharField(choices=[('Активный', 'Активный'), ('Горящий', 'Горящий'), ('Звершенный', 'Звершенный')], default='Активный', max_length=30),
        ),
    ]
