# Generated by Django 4.1.2 on 2022-11-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_sell', '0005_requestsell_rieltor'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsell',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requestsell',
            name='status',
            field=models.CharField(choices=[('Теплый', 'Теплый'), ('Горящий', 'Горящий'), ('Завершенный', 'Завершенный')], default='Теплый', max_length=30),
        ),
    ]
