# Generated by Django 4.1.2 on 2022-11-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_sell', '0006_requestsell_finished_alter_requestsell_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsell',
            name='last_time_edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='requestsell',
            name='no_attention',
            field=models.BooleanField(default=False),
        ),
    ]
